# Generated by Django 4.2.8 on 2023-12-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketApi', '0002_alter_ticket_arrival_station_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(default=123, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
